version: "3"

services:
  # PostgreSQL 15
  postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:15.3-alpine
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      
volumes:
  db-data:
